### ISSUE TITLE
Python hacks

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/config-nvim#1]
## File types
* requirements.txt
* pyproject.toml
* *.py

## Plugins
* [x] ~~vim-toml~~ no need
* [x] requirements-txt-vim
* [x] ~~Some plugin for editing Python?~~ no need

**Comment by mnacamura** [comment]
All set.
