### ISSUE TITLE
Syntax hacks

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/config-nvim#11]
## TODO
- [x] Find more treesitter plugins

## Plugins
- [x] [nvim-treesitter/nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter)
- [x] [nvim-treesitter/nvim-treesitter-textobjects](https://github.com/nvim-treesitter/nvim-treesitter-textobjects)
- [x] ~~[RRethy/nvim-treesitter-textsubjects](https://github.com/RRethy/nvim-treesitter-textsubjects)~~ Supported languages are not so many.
- [x] ~~[wellle/targets.vim](https://github.com/wellle/targets.vim)~~ treesitter-textobjects suffices.

**Comment by mnacamura** [comment]
All set for the moment.
