### ISSUE TITLE
Markdown/LaTeX hacks

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/config-nvim#2]
## TODO
- [ ] #23

## Settings
* [x] [dkarter/bullets.vim](https://github.com/dkarter/bullets.vim)
* [x] ~~Enable to edit pandoc's [simple table](https://pandoc.org/MANUAL.html#extension-simple_tables) in [dhruvasagar/vim-table-mode](https://github.com/dhruvasagar/vim-table-mode)?~~ It looks like pandoc's `simple_tables` and `multiline_tables` are not supported.

## Markdown plugins
* [x] [ellisonleao/glow.nvim](https://github.com/ellisonleao/glow.nvim)
* [x] ~~[vim-pandoc/vim-pandoc](https://github.com/vim-pandoc/vim-pandoc)~~
* [x] [vim-pandoc/vim-pandoc-syntax](https://github.com/vim-pandoc/vim-pandoc-syntax)
* [x] [rhysd/vim-gfm-syntax](https://github.com/rhysd/vim-gfm-syntax)
* [x] [dhruvasagar/vim-table-mode](https://github.com/dhruvasagar/vim-table-mode)
* [x] [crispgm/telescope-heading.nvim](https://github.com/crispgm/telescope-heading.nvim)

## LaTeX plugins
* [x] [texlab](https://github.com/latex-lsp/texlab) ~~or [vimtex](https://github.com/lervag/vimtex)~~ This is a language server.
* [x] [nvim-telescope/telescope-bibtex.nvim](https://github.com/nvim-telescope/telescope-bibtex.nvim) (This can be used in markdown actually)

**Comment by mnacamura** [comment]
Almost done. close it.
