### ISSUE TITLE
LSP hacks

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/config-nvim#3]
## Settings
* [x] Fix LSP key binds; ~~maybe with [nanotee/nvim-lsp-basics](https://github.com/nanotee/nvim-lsp-basics)?~~
* [ ] #30
* [x] Set up `LspReferenecText`, `LspReferenceRead`, and `LspRerefenceWrite` highlight colors [[code]](https://github.com/mnacamura/config-nvim/blob/efa017db4d792ca6958a1a67ae88e032c31e6c7e/lua/my/lspsettings.lua#L48-L53) (done by lsp-colors.nvim)

## Plugins
- [x] [RishabhRD/nvim-lsputils](https://github.com/RishabhRD/nvim-lsputils) ~~or [tami5/lspsaga.nvim](https://github.com/tami5/lspsaga.nvim) or [ray-x/navigator.lua](https://github.com/ray-x/navigator.lua)~~
- [x] [onsails/lspkind-nvim](https://github.com/onsails/lspkind-nvim)
- [ ] [jubnzv/virtual-types.nvim](https://github.com/jubnzv/virtual-types.nvim)
- [x] ~~[mfussenegger/nvim-lint](https://github.com/mfussenegger/nvim-lint) or~~ [jose-elias-alvarez/null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim) in place of ALE
- [x] ~~[simrat39/symbols-outline.nvim](https://github.com/simrat39/symbols-outline.nvim) or [liuchengxu/vista.vim](https://github.com/liuchengxu/vista.vim)~~: might be unneeded if using telescope
- [x] ~~[folke/trouble.nvim](https://github.com/folke/trouble.nvim)~~: might be unneeded if using telescope
- [x] [folke/lsp-colors.nvim](https://github.com/folke/lsp-colors.nvim) ~~Srcery has LSP colors.~~

**Comment by mnacamura** [comment]
Close for the moment
