### ISSUE TITLE
Misc. plugins

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/config-nvim#4]
## Marks

- [x] [chentau/marks.nvim](https://github.com/chentau/marks.nvim)

## Color

- [x] ~~[folke/twilight.nvim](https://github.com/folke/twilight.nvim)~~ No need

## Colorscheme Creation

- [x] ~~[Iron-E/nvim-highlite](https://github.com/Iron-E/nvim-highlite)~~ already created a colorscheme from highlite

## Colorscheme

- [x] [srcery-colors/srcery-vim](https://github.com/srcery-colors/srcery-vim)
    + ~~TODO: Replace it with nvim-highlite's.~~ Replaced.

## Icon

- [x] [kyazdani42/nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons)

## Neovim Lua development

- [x] [nvim-lua/plenary.nvim](https://github.com/nvim-lua/plenary.nvim)
- [x] [nvim-lua/popup.nvim](https://github.com/nvim-lua/popup.nvim)
- [x] [tjdevries/astronauta.nvim](https://github.com/tjdevries/astronauta.nvim)

## Statusline

- [x] [famiu/feline.nvim](https://github.com/famiu/feline.nvim)

## Cursorline

- [x] [yamatsum/nvim-cursorline](https://github.com/yamatsum/nvim-cursorline)

## Indent

- [x] ~~[lukas-reineke/indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim)~~
  ~~or [haringsrob/nvim_context_vt](https://github.com/haringsrob/nvim_context_vt)~~ No need

## Git

- [x] [lewis6991/gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)
- [x] ~~[tveskag/nvim-blame-line](https://github.com/tveskag/nvim-blame-line)~~
  ~~or [f-person/git-blame.nvim](https://github.com/f-person/git-blame.nvim)~~ satisfied with `<Leader>hb` provided by gitsigns.nvim.

## Comment

- [x] [b3nj5m1n/kommentary](https://github.com/b3nj5m1n/kommentary)

## Quickfix

- [x] [gitlab:yorickpeterse/nvim-pqf](https://gitlab.com/yorickpeterse/nvim-pqf)

## Motion

- [x] [chaoren/vim-wordmotion](https://github.com/chaoren/vim-wordmotion)
- [x] [ggandor/lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim)
    + in place of [rhysd/clever-f.vim](https://github.com/rhysd/clever-f.vim): `sr` conflicts with [vim-sandwitch](https://github.com/machakann/vim-sandwich)'s

## Search

- [x] [thinca/vim-visualstar](https://github.com/thinca/vim-visualstar)

## Editing support

- [x] ~~[RRethy/nvim-align](https://github.com/RRethy/nvim-align) in place of vim-easy-align~~
    + Nowadays all things like this are done by formatters.
- [ ] [windwp/nvim-autopairs](https://github.com/windwp/nvim-autopairs) or [steelsojka/pears.nvim](https://github.com/steelsojka/pears.nvim)
- [x] [monaqa/dial.nvim](https://github.com/monaqa/dial.nvim)
- [x] ~~[mizlan/iswap.nvim](https://github.com/mizlan/iswap.nvim)~~ No need
- [x] [nacro90/numb.nvim](https://github.com/nacro90/numb.nvim)
- [x] ~~[abecodes/tabout.nvim](https://github.com/abecodes/tabout.nvim)~~ No need
- [x] [ethanholz/nvim-lastplace](https://github.com/ethanholz/nvim-lastplace)

## Command line

- [x] [tpope/vim-rsi](https://github.com/tpope/vim-rsi)
- [x] ~~[gelguy/wilder.nvim](https://github.com/gelguy/wilder.nvim)~~ No need

## Split and Window

- [x] ~~[gitlab.com/yorickpeterse/nvim-window](https://gitlab.com/yorickpeterse/nvim-window)~~ in window-selecting mode, `<C-c>` breaks behavior and floating windows indicating keys remain.

**Comment by mnacamura** [comment]
Almost done. Close it.
