### ISSUE TITLE
Telescope hacks

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/config-nvim#8]
## TODO
- [ ] #25
- [ ] #27 

## Settings
- [x] Set basic keymaps
- [ ] #29

## Plugins
- [x] [nvim-telescope/telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)
- [x] ~~[folke/todo-comments.nvim](https://github.com/folke/todo-comments.nvim)~~
- [x] ~~[nvim-telescope/telescope-frecency.nvim](https://github.com/nvim-telescope/telescope-frecency.nvim)?~~
- [x] ~~[nvim-telescope/telescope-hop.nvim](https://github.com/nvim-telescope/telescope-hop.nvim)?~~
- [x] [nvim-telescope/telescope-symbols.nvim](https://github.com/nvim-telescope/telescope-symbols.nvim)

**Comment by mnacamura** [comment]
Close for the moment.
